# Generated by Django 4.0.2 on 2022-02-07 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 6, 48, 11, 163988, tzinfo=utc)),
        ),
    ]
